import { LucideIcon, Package, ShoppingCart, ShoppingBag, Warehouse, Settings, MessageSquare, Users, Wallet, Banknote, Truck, Map, ScanBarcode, Wrench, Factory, HardHat } from "lucide-react";
import type { ModuleId } from "@/core/permissions/usePermissions";

export type ModuleMenuItem = {
  label: string;
  to: string;
  icon?: LucideIcon;
  section?: string;
};

export type ModuleDef = {
  id: ModuleId | "settings";
  name: string;
  shortName: string;
  icon: LucideIcon;
  color: string; // tailwind bg color class
  basePath: string;
  description: string;
  menu: ModuleMenuItem[];
};

export const MODULES: ModuleDef[] = [
  {
    id: "sales",
    name: "Vendas",
    shortName: "Vendas",
    icon: ShoppingCart,
    color: "bg-[hsl(263_67%_56%)]",
    basePath: "/sales",
    description: "Cotações, pedidos, clientes e pipeline",
    menu: [
      { section: "Vendas", label: "Cotações", to: "/sales/quotations" },
      { section: "Vendas", label: "Pedidos", to: "/sales/orders" },
      { section: "Vendas", label: "Stock", to: "/sales/stock" },
      { section: "Cadastros", label: "Clientes", to: "/sales/customers" },
      { section: "Configuração", label: "Tabelas de Preço", to: "/sales/pricelists" },
      { section: "Configuração", label: "Regras de Entrega", to: "/sales/delivery-rules" },
      { section: "Relatórios", label: "Vendas por Estado", to: "/reports/sales" },
    ],
  },
  {
    id: "purchase",
    name: "Compras",
    shortName: "Compras",
    icon: ShoppingBag,
    color: "bg-[hsl(217_91%_60%)]",
    basePath: "/purchase",
    description: "RFQs, pedidos de compra e fornecedores",
    menu: [
      { section: "Compras", label: "Pedidos de Compra", to: "/purchase/orders" },
      { section: "Compras", label: "Necessidades de Compra", to: "/purchase/needs" },
      { section: "Compras", label: "Kanban RFQ", to: "/purchase/kanban" },
      { section: "Cadastros", label: "Fornecedores", to: "/purchase/suppliers" },
      { section: "Relatórios", label: "Compras por Estado", to: "/reports/purchase" },
    ],
  },
  {
    id: "inventory",
    name: "Inventário",
    shortName: "Stock",
    icon: Warehouse,
    color: "bg-[hsl(142_71%_38%)]",
    basePath: "/inventory",
    description: "Operações WMS, transferências e regras de stock",
    menu: [
      { section: "Operações", label: "Visão Geral", to: "/inventory" },
      { section: "Operações", label: "Cronograma", to: "/inventory/schedule" },
      { section: "Operações", label: "Recebimentos", to: "/inventory/receipts" },
      { section: "Operações", label: "Transferências", to: "/inventory/transfers" },
      { section: "Operações", label: "Lotes (Batch)", to: "/inventory/batches" },
      { section: "Operações", label: "Ondas (Wave)", to: "/inventory/waves" },
      { section: "Operações", label: "Códigos de Barras (App)", to: "/barcode" },
      { section: "Operações", label: "Movimentos", to: "/inventory/moves" },
      { section: "Operações", label: "Ajustes", to: "/inventory/adjustments" },
      { section: "Qualidade", label: "Danificados", to: "/inventory/damaged" },
      { section: "Qualidade", label: "Quarentena", to: "/inventory/quarantine" },
      { section: "Relatórios", label: "Kardex", to: "/inventory/kardex" },
      { section: "Relatórios", label: "Stock por Produto", to: "/reports/stock" },
      { section: "Relatórios", label: "Lotes/Séries", to: "/inventory/lots" },
      { section: "Configuração", label: "Armazéns", to: "/inventory/warehouses" },
      { section: "Configuração", label: "Locais", to: "/inventory/locations" },
      { section: "Configuração", label: "Locais (árvore)", to: "/inventory/locations-tree" },
      { section: "Relatórios", label: "Stock por Bin", to: "/inventory/bins" },
      { section: "Configuração", label: "Carrinhas / Veículos", to: "/inventory/vehicles" },
      { section: "Configuração", label: "Transportadoras", to: "/inventory/carriers" },
      { section: "Configuração", label: "Regras de Reabastecimento", to: "/inventory/reordering" },
    ],
  },
  {
    id: "products",
    name: "Produtos",
    shortName: "Produtos",
    icon: Package,
    color: "bg-[hsl(38_92%_50%)]",
    basePath: "/products",
    description: "Catálogo, variantes e BOM",
    menu: [
      { section: "Catálogo", label: "Produtos", to: "/products" },
      { section: "Catálogo", label: "Categorias", to: "/products/categories" },
      { section: "Catálogo", label: "Atributos", to: "/products/attributes" },
      { section: "Engenharia", label: "Listas de Materiais (BOM)", to: "/products/bom" },
    ],
  },
  {
    id: "hr" as any,
    name: "Recursos Humanos",
    shortName: "RH",
    icon: Users,
    color: "bg-[hsl(340_82%_52%)]",
    basePath: "/hr",
    description: "Colaboradores, ausências e assiduidade",
    menu: [
      { section: "Pessoas", label: "Colaboradores", to: "/hr/employees" },
      { section: "Pessoas", label: "Departamentos", to: "/hr/departments" },
      { section: "Assiduidade", label: "Relógio de Ponto", to: "/hr/attendance" },
      { section: "Assiduidade", label: "Registos", to: "/hr/attendances" },
      { section: "Ausências", label: "Pedidos", to: "/hr/leaves" },
    ],
  },
  {
    id: "finance" as any,
    name: "Financeiro",
    shortName: "Financeiro",
    icon: Wallet,
    color: "bg-[hsl(160_84%_39%)]",
    basePath: "/finance",
    description: "Recebimentos, contas a pagar e centros de custo",
    menu: [
      { section: "Visão Geral", label: "Dashboard", to: "/finance" },
      { section: "Operações", label: "Recebimentos", to: "/finance/payments" },
      { section: "Operações", label: "A Receber", to: "/finance/receivables" },
      { section: "Operações", label: "Confirmações", to: "/finance/pending" },
      { section: "Operações", label: "Contas a Pagar", to: "/finance/payables" },
      { section: "Operações", label: "Despesas Fixas", to: "/finance/recurring" },
      { section: "Configuração", label: "Diários", to: "/finance/journals" },
      { section: "Configuração", label: "Métodos de Pagamento", to: "/finance/methods" },
      { section: "Configuração", label: "Centros de Custo", to: "/finance/cost_centers" },
      { section: "Operações", label: "Entregas e Caixa", to: "/finance/handovers" },
    ],
  },
  {
    id: "cashbox" as any,
    name: "Caixa",
    shortName: "Caixa",
    icon: Banknote,
    color: "bg-[hsl(24_95%_53%)]",
    basePath: "/cashbox",
    description: "Caixas de loja, sessões e movimentos diários",
    menu: [
      { section: "Caixas", label: "Caixas", to: "/cashbox" },
    ],
  },
  {
    id: "routes" as any,
    name: "Rotas",
    shortName: "Rotas",
    icon: Map,
    color: "bg-[hsl(173_80%_36%)]",
    basePath: "/routes",
    description: "Cronograma de rotas, zonas e entregas agendadas",
    menu: [
      { section: "Rotas", label: "Cronograma", to: "/routes" },
      { section: "Operações", label: "Levantamentos", to: "/m5/pickups" },
      { section: "Operações", label: "Transportadora externa", to: "/m5/carrier" },
      { section: "Configuração", label: "Zonas", to: "/routes/zones" },
    ],
  },
  {
    id: "delivery" as any,
    name: "Entregas",
    shortName: "Entregas",
    icon: Truck,
    color: "bg-[hsl(150_70%_40%)]",
    basePath: "/delivery",
    description: "App do entregador: scan, entrega e cobrança",
    menu: [
      { section: "Entregas", label: "Hoje", to: "/delivery" },
      { section: "Entregas", label: "Caixa", to: "/delivery/cashbox" },
    ],
  },
  {
    id: "barcode" as any,
    name: "Código de Barras",
    shortName: "Barcode",
    icon: ScanBarcode,
    color: "bg-[hsl(280_70%_50%)]",
    basePath: "/barcode",
    description: "App de scan: receção, picking, transferências e localizações",
    menu: [
      { section: "Scan", label: "Início", to: "/barcode" },
      { section: "Scan", label: "Receção", to: "/barcode/op/incoming" },
      { section: "Scan", label: "Expedição", to: "/barcode/op/outgoing" },
      { section: "Scan", label: "Transferência interna", to: "/barcode/op/internal" },
      { section: "Scan", label: "Picking (todos)", to: "/barcode/op/all" },
      { section: "Scan", label: "Arrumar", to: "/barcode/putaway" },
      { section: "Scan", label: "Lotes (Batch)", to: "/barcode/batches" },
      { section: "Scan", label: "Ondas (Wave)", to: "/barcode/waves" },
      { section: "Consulta", label: "Produto", to: "/barcode/lookup/product" },
      { section: "Consulta", label: "Localização", to: "/barcode/lookup/location" },
    ],
  },
  {
    id: "discuss" as any,
    name: "Conversas",
    shortName: "Chat",
    icon: MessageSquare,
    color: "bg-[hsl(199_89%_48%)]",
    basePath: "/discuss",
    description: "Canais de equipa e mensagens diretas",
    menu: [{ section: "Conversas", label: "Canais", to: "/discuss" }],
  },
  {
    id: "service" as any,
    name: "Assistência",
    shortName: "Assistência",
    icon: Wrench,
    color: "bg-[hsl(35_90%_55%)]",
    basePath: "/service",
    description: "Assistência, helpdesk e portal cliente",
    menu: [
      { section: "Assistência", label: "Pedidos", to: "/service/requests" },
      { section: "Assistência", label: "Reparações", to: "/service/repairs" },
      { section: "Helpdesk", label: "Tickets", to: "/helpdesk/tickets" },
    ],
  },
  {
    id: "helpdesk" as any,
    name: "Helpdesk",
    shortName: "Helpdesk",
    icon: Wrench,
    color: "bg-[hsl(35_90%_55%)]",
    basePath: "/helpdesk",
    description: "Tickets de clientes e atendimento",
    menu: [
      { section: "Helpdesk", label: "Tickets", to: "/helpdesk/tickets" },
      { section: "Helpdesk", label: "Portal Cliente", to: "/helpdesk/portal-tokens" },
      { section: "Assistência", label: "Pedidos de assistência", to: "/service/requests" },
      { section: "Assistência", label: "Reparações", to: "/service/repairs" },
    ],
  },
  {
    id: "manufacturing" as any,
    name: "Manufatura",
    shortName: "MRP",
    icon: Factory,
    color: "bg-[hsl(210_60%_45%)]",
    basePath: "/manufacturing",
    description: "Ordens de fabricação, BOM e planeamento",
    menu: [
      { section: "Visão Geral", label: "Dashboard", to: "/manufacturing" },
      { section: "Produção", label: "Ordens de Fabricação", to: "/manufacturing/orders" },
      { section: "Produção", label: "Planeamento", to: "/manufacturing/planning" },
      { section: "Configuração", label: "Centros de Trabalho", to: "/manufacturing/work-centers" },
      { section: "Configuração", label: "Operações", to: "/manufacturing/operations" },
      { section: "Engenharia", label: "Listas de Materiais (BOM)", to: "/products/bom" },
    ],
  },
  {
    id: "shop_floor" as any,
    name: "Chão de Fábrica",
    shortName: "Fábrica",
    icon: HardHat,
    color: "bg-[hsl(20_85%_50%)]",
    basePath: "/shop-floor",
    description: "Painel operacional do chão de fábrica",
    menu: [
      { section: "Operação", label: "Painel", to: "/shop-floor" },
      { section: "Qualidade", label: "Controle de Qualidade", to: "/shop-floor/quality" },
    ],
  },
  {
    id: "settings",
    name: "Configurações",
    shortName: "Config",
    icon: Settings,
    color: "bg-[hsl(222_22%_30%)]",
    basePath: "/settings",
    description: "Empresa, usuários, grupos, módulos",
    menu: [
      { section: "Geral", label: "Apps Instalados", to: "/settings/apps" },
      { section: "Usuários", label: "Usuários", to: "/settings/users" },
      { section: "Usuários", label: "Grupos & Permissões", to: "/settings/groups" },
      { section: "Empresa", label: "Empresa", to: "/settings/company" },
      { section: "Empresa", label: "Lojas", to: "/settings/stores" },
    ],
  },
];

export const getModuleByPath = (pathname: string) =>
  MODULES.find((m) => pathname === m.basePath || pathname.startsWith(m.basePath + "/")) ?? null;
